### ISSUE TITLE
[BUG] All components are rendering to view

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/reactsocialnetwork#11]
**Describe the bug**
[App]

All of the components display when the app is running.

These panels/components should only be visible through clicking on the navigation && icons when the user icon is clicked.

**To Reproduce**
1. May need to `npm i` or `npm install` as I did not include my local node_modules dir in the initial commit & push  upload
2.  run `npm start` in the project root to start the dev server.
3.  browser will open. 

The tab shows components which are related to components which should only show when clicking on a choice in the Uaer Icon menu, which has not currently been completed yet.

**Expected behavior**

The main app view should be a 3 column view in Desktop view.  200-250px left and right columns.. leaving about 1400+ px for a center column which shows posts, etc.

User should be able to click on the user icon and access the panels.

**Desktop (please complete the following information):**
   Linux, 64bit
   Firefox 
   107

**Additional context**

Complete the user icon menu.

**Comment by KaptainCS3** [comment]
!assign

**Comment by gbowne1** [comment]
@KaptainCS3 are you wishing to get assigned to this task?

**Comment by KaptainCS3** [comment]
yes

**Comment by gbowne1** [comment]
Ok. if you would lke to get assigned, just ask. Thank you.

**Comment by gbowne1** [comment]
I think this is a routing problem.  

Only components that should show in the center of the view (at least on desktop view) are Post.jsx and a  component that shows the post after being posted underneath that. The rest are only displayed when the user clicks on a button.

**Comment by manuel12** [comment]
I have an idea how to fix this, could you assign it to me? :)

**Comment by gbowne1** [comment]
Ok @manuel12 :+1:

**Comment by manuel12** [comment]
Hello. I have one question regarding this issue: which should be the component shown at "http://localhost:3000/" ?
The routes on App.js show /settings, /profile, /dashboard and /terms but nothing is set for the "/" home route.

**Comment by gbowne1** [comment]
@manuel12 

So zi never finished the routing inside the App or the Links snd Routing to and from the compoments.

To answer your question, I believe  that would depend a lot on user state.  

Is the user a admin, a moderator or simply a user?  and well each could have varying levels of access. Has the user not registered yet? Not completed their profile? Redirect to their profile with the means to edit and submit it.  

The average user thoughh should see posts and the completed posted posts in the feed.  

When the drawer is closed,  we can stick stuff under it.  

Ideas? @manuel12 @pawel975 @Dylan-Clarry 

But,

**Comment by manuel12** [comment]
Just to give some more context regarding this issue:
The reason that all components are rendering into view is due to this code found near the bottom of App.js:
```          
<main className="Main-app">
 <section className="Section-app">
  <UserProfile toggle={toggle} />
  <Dashboard toggle={toggle} />
  <Friends toggle={toggle} />
  <Profile toggle={toggle} />
  <Settings toggle={toggle} />
  <Post toggle={toggle} />
 </section>
</main>
```

This is basically rendering all the components one on top of another. 

As far as I understand we should instead only leave one component here, which will be the component loaded at the "/" route, the home route for that I need to know which component is the one that should be shown by default.

**Comment by gbowne1** [comment]
I was not happy with this solution either but till the Nav was complete I did not feel comfortable not being able to see components in the view.

They can now be returned to their natural state in the UI accessible by the menu buttons.. with the exception of a few.

**Comment by manuel12** [comment]
Ok, with the current information I propose this solution:

All the components that are currently being displayed one on top of another will be not be shown anymore.

Instead I propose to show a component by default, the Dashboard for example(if this component is not the appropriate one we can later change it for another component) on route "/". I will add this route to the current routes.

The other components that currently are currently shown (UserProfile, Friends, Profile, Settings, etc) will not be shown by default. Instead they will be reachable if the user clicks on any of the IconButtons in the header(I will wrap the relevant IconButtons with anchor tags and href to the appropriate route. So for example the Settings button will have href="/settings").

And finally I propose to add an anchor tag with href="/" to the header logo so that user can come back to homepage by clicking on it.

I'm open to modifications and suggestions for this solution :) if it's ok with everybody then I will implement this and make a PR in a few moments.

**Comment by gbowne1** [comment]
@manuel12 

Ok.  Sounds good to me as a part of first steps to the next level

**Comment by gbowne1** [comment]
Oh and before there was no good way to close each component either or put them away as it were.
